version: '3.4'

services:
  ms-sublearn-provider:
    image: almazic91/sub-learn-provider:${PROVIDER_IMAGE_VERSION}
    depends_on:
      - ms-sublearn-back
    restart: always
    ports:
      - 8085:8080
    environment:
      SPRING_PROFILES_ACTIVE: default
      SERVER_PORT: 8080
      SUBLEARN_BACK_URL: http://ms-sublearn-back:8080/api
      SUBLEARN_BACK_LOGIN: ${SUBLEARN_BACK_LOGIN}
      SUBLEARN_BACK_PASSWORD: ${SUBLEARN_BACK_PASSWORD}
      IMDB_API_KEY: ${IMDB_API_KEY}
      OPENSUBTITLES_USERAGENT: ${OPENSUBTITLES_USERAGENT}
